### ISSUE TITLE
Im creating "My favs new episodes" page

### ISSUE THREAD

**Issue by Tommixoft** [Ksantor/plugin.video.lostfilm.tv#3]
Hi dont know how to inform you so used issues. Im creating page where people can see new episodes of their favorited series. So you if thinking to do it you can skip it :) when i will do i will commit and send you Pull request and you then decide merge or not :)

**Comment by capris** [comment]
i think it is very good idea, this feature i am waiting most

**Comment by Tommixoft** [comment]
i was almost done but lostfilm changed again something and now it's not working and i cant figureout how can i get empty div with that HTMLparser that plugin uses..so few days i think to bring this function

**Comment by Tommixoft** [comment]
@capris  you can start using my version https://github.com/Tommixoft/plugin.video.lostfilm.tv for more features if you dont use old one, cause i know someone fixed the old one. But i still will be creating new one. I think old website will be closed soon.

**Comment by capris** [comment]
Cool :), how about description about series, and second thing i am missing : release date.

**Comment by capris** [comment]
And one more interesting thing, how do you think, is it possible to make sections (pages) like favorites and other a little bit faster loading, because now it is five sec or on all series even minute or more

**Comment by capris** [comment]
Sorry it seams that loading of pages is slow only on my tv, just tested on android phone and everything is super fast, so sorry for my previous post

**Comment by Ksantor** [comment]
Closing this issue, since it is no more related to current repo.
